<a href="https://colab.research.google.com/github/Palak1608/Data-Science-Lab-Work/blob/main/Lab4_Data_Analysis_Pandas/lab4_data_analysis_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#pip install pandas

Pandas (stands for Python Data Analysis) is an open-source software library designed for data manipulation and analysis.

Built on top of NumPy, efficiently manages large datasets, offering tools for data cleaning, transformation, and analysis.
Tools for working with time series data, including date range generation and frequency conversion. For example, we can convert date or time columns into pandas’ datetime types using pd.to_datetime(), or specify parse_dates=True during CSV loading.
Seamlessly integrates with other Python libraries like NumPy, Matplotlib, and scikit-learn.
Revolves around two primary Data structures: Series (1D) and DataFrame (2D).
Provides methods like .dropna() and .fillna() to handle missing values seamlessly.

What is Pandas Used for?

Reading and writing data from various file formats like CSV, Excel and SQL databases.
Cleaning and preparing data (handling missing values, filtering, removing duplicates).
Merging, joining, and reshaping datasets.
Performing statistical analysis and descriptive statistics.
Visualizing data quickly.

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [3]:
a = np.array([1, 2, "aa", "bb", 34, 45])
print(a.dtype) ### array  contains both  integer and string so d type use  convert  all elements into in string  type keep with single data
print(a)

<U21
['1' '2' 'aa' 'bb' '34' '45']

In [4]:
S = pd.Series(a, index=list(range(10, 16))) ##pd.series use pandas  creat series
S

10     1
11     2
12    aa
13    bb
14    34
15    45
dtype: object

In [5]:
lt = [1, 2, "aa", "bb", 34, 45]
type(lt)

list

In [7]:
mydic = {"Snake":0, "Birds": 2, "Cat": 4, "Human": 2}
myD = pd.Series(mydic)
myD

Snake    0
Birds    2
Cat      4
Human    2
dtype: int64

In [8]:
myD["Human"]

np.int64(2)

In [9]:
s=pd.Series(100,index =list(range(5,10)))
s

5    100
6    100
7    100
8    100
9    100
dtype: int64

In [32]:
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [36]:
df = pd.read_csv("German-Credit_2.xls", sep=",")
df.head()

   OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
0    1         0        4         4           4                 4    2
1    2         1        2         0           2                 2    2
2    3         3        4         0           3                 3    1
3    4         0        2         0           3                 4    2
4    5         0        3         0           2                 4    2

In [37]:
df.tail(3)

      OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
997   998         3        2         0           4                 4    2
998   999         0        2         0           2                 4    2
999  1000         1        4         1           0                 4    2

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OBS               1000 non-null   int64
 1   CHK_ACCT          1000 non-null   int64
 2   HISTORY           1000 non-null   int64
 3   SAV_ACCT          1000 non-null   int64
 4   EMPLOYMENT        1000 non-null   int64
 5   PRESENT_RESIDENT  1000 non-null   int64
 6   JOB               1000 non-null   int64
dtypes: int64(7)
memory usage: 54.8 KB

In [39]:
df.columns

Index(['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT',
       'PRESENT_RESIDENT', 'JOB'],
      dtype='object')

In [41]:
df.mean()

OBS                 500.500
CHK_ACCT              1.577
HISTORY               2.545
SAV_ACCT              1.105
EMPLOYMENT            2.384
PRESENT_RESIDENT      2.845
JOB                   1.904
dtype: float64

In [42]:
df.std()

OBS                 288.819436
CHK_ACCT              1.257638
HISTORY               1.083120
SAV_ACCT              1.580023
EMPLOYMENT            1.208306
PRESENT_RESIDENT      1.103718
JOB                   0.653614
dtype: float64

In [43]:
df.describe()

,OBS,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,1.577000,2.54500,1.105000,2.384000,2.845000,1.904000
std,288.819436,1.257638,1.08312,1.580023,1.208306,1.103718,0.653614
min,1.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,250.750000,0.000000,2.00000,0.000000,2.000000,2.000000,2.000000
50%,500.500000,1.000000,2.00000,0.000000,2.000000,3.000000,2.000000
75%,750.250000,3.000000,4.00000,2.000000,4.000000,4.000000,2.000000
max,1000.000000,3.000000,4.00000,4.000000,4.000000,4.000000,3.000000

In [44]:
df.describe(include="all")

,OBS,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,1.577000,2.54500,1.105000,2.384000,2.845000,1.904000
std,288.819436,1.257638,1.08312,1.580023,1.208306,1.103718,0.653614
min,1.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,250.750000,0.000000,2.00000,0.000000,2.000000,2.000000,2.000000
50%,500.500000,1.000000,2.00000,0.000000,2.000000,3.000000,2.000000
75%,750.250000,3.000000,4.00000,2.000000,4.000000,4.000000,2.000000
max,1000.000000,3.000000,4.00000,4.000000,4.000000,4.000000,3.000000

#loc and iloc in pandas

In [46]:
df.loc[1:5]

   OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
1    2         1        2         0           2                 2    2
2    3         3        4         0           3                 3    1
3    4         0        2         0           3                 4    2
4    5         0        3         0           2                 4    2
5    6         3        2         4           2                 4    1

In [47]:
df.iloc[1:5,2:9]

   HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
1        2         0           2                 2    2
2        4         0           3                 3    1
3        2         0           3                 4    2
4        3         0           2                 4    2

In [48]:
import pandas as pd

a = [10, 20, 30, 40, 50, 60]

S = pd.Series(a, index=list(range(10,16)))
print(S)

10    10
11    20
12    30
13    40
14    50
15    60
dtype: int64

In [51]:
print(df.columns)

Index(['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT',
       'PRESENT_RESIDENT', 'JOB'],
      dtype='object')

In [52]:
df.head()

   OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
0    1         0        4         4           4                 4    2
1    2         1        2         0           2                 2    2
2    3         3        4         0           3                 3    1
3    4         0        2         0           3                 4    2
4    5         0        3         0           2                 4    2

In [53]:
meanamo = df.iloc[:, 4].mean()
print(meanamo)

2.384

This program shows how to create a Series in Pandas using user-defined index values.
It helps to understand how data and index work together in Pandas.


Author: Palak Salunkhe